// Code generated by goctl. DO NOT EDIT.
package types

type AddUserRequest struct {
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type AddUserResponse struct {
	BaseMsgResp
	Data User `json:"data"`
}

type BaseDataInfo struct {
	Code uint32 `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data,omitempty"`
}

type BaseListInfo struct {
	Total uint64 `json:"total"`
}

type BaseMsgResp struct {
	Code uint32 `json:"code"`
	Msg  string `json:"msg"`
}

type BatchAddUserRequest struct {
	Data []AddUserRequest `json:"data"`
}

type BatchAddUserResponse struct {
	BaseMsgResp
	Data []User `json:"data"` // 响应结构体data
}

type BatchDeleteUserRequest struct {
	Ids []int64 `json:"ids"` // 要删除的用户id列表
}

type DeleteUserRequest struct {
	Id int64 `path:"id"` // 要删除的id
}

type DetailUserRequest struct {
	Id int64 `path:"id"`
}

type DetailUserResponse struct {
	BaseMsgResp
	Data User `json:"data"`
}

type ListUserInfo struct {
	BaseListInfo
	List []User `json:"list"` // 用户信息列表
}

type ListUserRequest struct {
	PageReqInfo
	Keyword string `form:"keyword,optional"` // 查询name关键词
}

type ListUserResponse struct {
	BaseMsgResp
	Data ListUserInfo `json:"data"` // 响应结构体data
}

type PageReqInfo struct {
	Page     uint64 `form:"page,optional,default=1"`
	PageSize uint64 `form:"pageSize,optional,default=20" validate:"gte=1,lte=100"`
}

type UpdateUserRequest struct {
	Id       int64  `path:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type UpdateUserResponse struct {
	BaseMsgResp
	Data User `json:"data"` // 响应结构体data
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}
